openapi: 3.0.3
info:
  title: Projeto do SENAI Jandira - Professor Marcel
  description: |-
   API destinada a controle de alunos
  termsOfService: http://swagger.io/terms/
  contact:
    email: seunome@email.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://
paths:
  /v1/aluno:
    post:
      tags:
        - aluno
      summary: Adiciona um novo Aluno
      description: Adiciona um novo Aluno
      requestBody:
        description: JSON contendo os dados do anovo aluno a ser inserido no sistema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aluno'
        required: true
      responses:
        '201':
          description: Successful operation
        '400':
          description: Invalid input
    get:
      tags:
        - aluno
      summary: Lista todos os alunos
      description: Listagem de todos os alunos registrados no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aluno'          
           
        '404':
          description: Not Found
  /v1/aluno/{id}:
    get:
      tags:
        - aluno
      summary: Busca um aluno prlo ID
      description: Retorna um aluno pelo ID
      parameters:
        - name: id
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aluno'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
    put:
      tags:
        - aluno
      summary: Update an existing pet
      description: Update an existing pet by Id
      parameters:
        - name: id
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aluno'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
       
    delete:
      tags:
        - aluno
      summary: Delete aluno
      description: Excluir um aluno
      parameters:
        - name: id
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
components:
  schemas:
    Aluno:
      required:
        - nome
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        celular:
          type: string
        email:
          type: string
  requestBodies:
    Aluno:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Aluno'
    
